name: Build APKs
on:
  workflow_dispatch: {}     # adds a "Run workflow" button
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK (cmdline-tools)
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install platforms & build tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Make sure Gradle can find the SDK even without Android Studio
      - name: Write local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Build APKs (Gradle 8.7)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.7'
          arguments: ':deviceapp:assembleDebug :wearapp:assembleDebug'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: |
            deviceapp/build/outputs/apk/debug/*-debug.apk
            wearapp/build/outputs/apk/debug/*-debug.apk
